# This is a basic workflow to help you get started with Actions

name: Python application test with Github Acions

on: [push]

jobs:
  build:
   
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v2
   - name: setup python 3.5
     uses: actions/setup-python@v1
     with:
        python-verion : 3.5
   - name: Install Dependencies
     run : |
      make install
   - name: Lint with Pylint
     run : |
      make lint
   - name: Test with Pytest
     run : |
      make test
  
